server:
  port: 8081

app:
  endpoints:
    shortest: shortest
    quickest: quickest

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka