server:
  port: 8001

zuul:
  routes:
    data:
      path: /data/**
      serviceId: itineraries-data

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    config:
      allowOverride: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka